# 🚀 **Transfer Learning with MobileNetV2**

### 📦 Import MobileNetV2

In [43]:
from keras.applications.mobilenet_v2 import MobileNetV2

model = MobileNetV2(weights="imagenet")
model.summary()

Model: "mobilenetv2_1.00_224"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_4       │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv1 (Conv2D)      │ (None, 112, 112,  │        864 │ input_layer_4[0]… │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bn_Conv1            │ (None, 112, 112,  │        128 │ Conv1[0][0]       │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv1_relu (ReLU)   │ (None, 112, 112,  │          0 │ bn_Conv1[0][0]    │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_dept… │ (None, 112, 112,  │        288 │ Conv1_relu[0][0]  │
│ (DepthwiseConv2D)   │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_dept… │ (None, 112, 112,  │        128 │ expanded_conv_de… │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_dept… │ (None, 112, 112,  │          0 │ expanded_conv_de… │
│ (ReLU)              │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_proj… │ (None, 112, 112,  │        512 │ expanded_conv_de… │
│ (Conv2D)            │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_proj… │ (None, 112, 112,  │         64 │ expanded_conv_pr… │
│ (BatchNormalizatio… │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_expand      │ (None, 112, 112,  │      1,536 │ expanded_conv_pr… │
│ (Conv2D)            │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_expand_BN   │ (None, 112, 112,  │        384 │ block_1_expand[0… │
│ (BatchNormalizatio… │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_expand_relu │ (None, 112, 112,  │          0 │ block_1_expand_B… │
│ (ReLU)              │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_pad         │ (None, 113, 113,  │          0 │ block_1_expand_r… │
│ (ZeroPadding2D)     │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_depthwise   │ (None, 56, 56,    │        864 │ block_1_pad[0][0] │
│ (DepthwiseConv2D)   │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_depthwise_… │ (None, 56, 56,    │        384 │ block_1_depthwis… │
│ (BatchNormalizatio… │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_depthwise_… │ (None, 56, 56,    │          0 │ block_1_depthwis… │
│ (ReLU)              │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_project     │ (None, 56, 56,    │      2,304 │ block_1_depthwis

 Total params: 3,538,984 (13.50 MB)

 Trainable params: 3,504,872 (13.37 MB)

 Non-trainable params: 34,112 (133.25 KB)

### ⬇️ Load and pre-process the data

In [ ]:
import numpy as np
from imageio import imread
from skimage.transform import resize
from keras.applications.mobilenet_v2 import preprocess_input

data = np.empty((40, 224, 224, 3))

for i in range(20):
  im = imread('datasets/dogs-with-gender/f{:02d}.jpg'.format(i+1))
  im = preprocess_input(im)
  im = resize(im, output_shape=(224, 224))
  data[i] = im

for i in range(20):
  im = imread('datasets/dogs-with-gender/m{:02d}.jpg'.format(i+1))
  im = preprocess_input(im)
  im = resize(im, output_shape=(224, 224))
  data[i+20] = im

In [45]:
print(data) # Normalized image data
print(f'min: {data.min()}, max: {data.max()}')

[[[[-0.67843139 -0.47450978 -0.56078434]
   [-0.52941179 -0.34901959 -0.39607841]
   [-0.44313723 -0.28627449 -0.38039213]
   ...
   [-0.28627449 -0.39607841 -0.27843136]
   [-0.30196077 -0.41176468 -0.29411763]
   [-0.32549018 -0.43529409 -0.31764704]]

  [[-0.82745099 -0.56862748 -0.98431373]
   [-0.47450978 -0.25490195 -0.57647061]
   [-0.17647058  0.0196079  -0.29411763]
   ...
   [-0.14509803 -0.25490195 -0.13725489]
   [-0.13725489 -0.24705881 -0.14509803]
   [-0.13725489 -0.24705881 -0.14509803]]

  [[-0.81176472 -0.49019605 -1.        ]
   [-0.34117645 -0.0745098  -0.73333335]
   [ 0.00392163  0.21568632 -0.32549018]
   ...
   [-0.05882353 -0.18431371 -0.09803921]
   [-0.01960784 -0.14509803 -0.05882353]
   [ 0.01176476 -0.11372548 -0.03529412]]

  ...

  [[ 0.27843142  0.05882359  0.03529418]
   [ 0.25490201  0.03529418  0.01176476]
   [ 0.20784318  0.01176476 -0.01960784]
   ...
   [ 0.01176476 -0.14509803 -0.13725489]
   [ 0.0196079  -0.13725489 -0.12941176]
   [ 0.04313731 

### 🏷️ Generate the lables

In [46]:
labels = np.empty(40, dtype=int)
labels[:20] = 0 # Female dogs
labels[20:] = 1 # Male dogs
print(labels) # Labels for the data

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


### 🐶 Generate predictions for dogs

In [47]:
from keras.applications.mobilenet_v2 import decode_predictions

predictions = model.predict(data)

for decoded_prediction in decode_predictions(predictions, top=1):
  for name, desc, score in decoded_prediction:
    print('- {} ({:.2f}%)'.format(desc, score * 100))

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 355ms/step
- kuvasz (49.89%)
- Bernese_mountain_dog (26.32%)
- Pekinese (93.71%)
- collie (13.72%)
- Pekinese (16.24%)
- Tibetan_mastiff (21.61%)
- bluetick (25.60%)
- Rottweiler (76.14%)
- Great_Dane (44.47%)
- Pembroke (12.65%)
- Walker_hound (74.10%)
- German_shepherd (42.91%)
- redbone (78.15%)
- Maltese_dog (85.18%)
- Siberian_husky (61.32%)
- dalmatian (87.47%)
- komondor (23.49%)
- dingo (66.58%)
- bluetick (45.97%)
- dingo (34.29%)
- kelpie (43.55%)
- black-and-tan_coonhound (22.03%)
- Rottweiler (43.49%)
- German_short-haired_pointer (57.46%)
- American_Staffordshire_terrier (43.68%)
- Dandie_Dinmont (74.33%)
- Walker_hound (50.51%)
- Labrador_retriever (39.85%)
- American_Staffordshire_terrier (97.94%)
- German_shepherd (62.45%)
- Great_Dane (79.72%)
- Great_Dane (41.93%)
- Labrador_retriever (86.18%)
- redbone (66.81%)
- German_shepherd (81.77%)
- boxer (79.90%)
- German_shepherd (53.02%)
- boxer (96.62%)
- black-and-tan_coonhound (66.84%)
- minia

### 🛠️ Modify the model

In [56]:
from keras.models import Model
from keras.layers import Dense

dog_output = Dense(2, activation="softmax") # Create a new output layer
dog_output = dog_output(model.layers[-2].output) # Connect the output layer to the last layer of the base model
dog_input = model.input # Get the input layer of the base model
dog_model = Model(inputs=dog_input, outputs=dog_output) # Create a new model with the input and output layers

for layer in dog_model.layers[:-1]:
  layer.trainable = False

### ⚙️ Compile the model

In [57]:
dog_model.compile(
  loss='sparse_categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

### 🦾 Training the model

In [50]:
dog_model.fit(
  x=data,
  y=labels,
  epochs=20,
  verbose=2
)

Epoch 1/20
2/2 - 1s - 698ms/step - accuracy: 0.4250 - loss: 0.8067
Epoch 2/20
2/2 - 0s - 94ms/step - accuracy: 0.5500 - loss: 0.6918
Epoch 3/20
2/2 - 0s - 94ms/step - accuracy: 0.6250 - loss: 0.6410
Epoch 4/20
2/2 - 0s - 95ms/step - accuracy: 0.8000 - loss: 0.5692
Epoch 5/20
2/2 - 0s - 95ms/step - accuracy: 0.7750 - loss: 0.5082
Epoch 6/20
2/2 - 0s - 95ms/step - accuracy: 0.7500 - loss: 0.4732
Epoch 7/20
2/2 - 0s - 94ms/step - accuracy: 0.7250 - loss: 0.4474
Epoch 8/20
2/2 - 0s - 95ms/step - accuracy: 0.7750 - loss: 0.4152
Epoch 9/20
2/2 - 0s - 95ms/step - accuracy: 0.8500 - loss: 0.3782
Epoch 10/20
2/2 - 0s - 95ms/step - accuracy: 0.9000 - loss: 0.3456
Epoch 11/20
2/2 - 0s - 95ms/step - accuracy: 0.9000 - loss: 0.3189
Epoch 12/20
2/2 - 0s - 95ms/step - accuracy: 0.9000 - loss: 0.2967
Epoch 13/20
2/2 - 0s - 95ms/step - accuracy: 0.9250 - loss: 0.2798
Epoch 14/20
2/2 - 0s - 95ms/step - accuracy: 0.9250 - loss: 0.2623
Epoch 15/20
2/2 - 0s - 94ms/step - accuracy: 0.9500 - loss: 0.2484
Epo

### 🐶 Generate predictions for trained data

In [53]:
preds = dog_model.predict(data)
print(preds.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step 
(40, 2)


In [54]:
np.argmax(preds, axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 🆕 Generate separate training and validation sets

In [55]:
training_data = np.empty((30, 224, 224, 3))
training_data[:15] = data[:15] # First 15 feamale dogs
training_data[15:] = data[20:35] # First 15 male dogs
training_labels = np.empty(30)
training_labels[:15] = 0 # Female dog
training_labels[15:] = 1 # Male dog

validation_data = np.empty((10, 224, 224, 3))
validation_data[:5] = data[15:20] # Last 5 female dogs
validation_data[5:] = data[35:] # Last 5 male dogs
validation_labels = np.empty(10)
validation_labels[:5] = 0 # Female dog
validation_labels[5:] = 1 # Male dog

### 🦾 Training with separate validation data
⚠️ Make sure that the modified model and the compiled model cells are run before running the following code

In [58]:
dog_model.fit(
  x=training_data,
  y=training_labels,
  epochs=20,
  verbose=2,
  validation_data=(validation_data, validation_labels)
)

Epoch 1/20
1/1 - 2s - 2s/step - accuracy: 0.5667 - loss: 0.6334 - val_accuracy: 0.4000 - val_loss: 0.9148
Epoch 2/20
1/1 - 0s - 209ms/step - accuracy: 0.7333 - loss: 0.5570 - val_accuracy: 0.5000 - val_loss: 0.9045
Epoch 3/20
1/1 - 0s - 199ms/step - accuracy: 0.8333 - loss: 0.4979 - val_accuracy: 0.5000 - val_loss: 0.8936
Epoch 4/20
1/1 - 0s - 199ms/step - accuracy: 0.9000 - loss: 0.4463 - val_accuracy: 0.5000 - val_loss: 0.8820
Epoch 5/20
1/1 - 0s - 197ms/step - accuracy: 0.9333 - loss: 0.4002 - val_accuracy: 0.6000 - val_loss: 0.8733
Epoch 6/20
1/1 - 0s - 199ms/step - accuracy: 0.9333 - loss: 0.3599 - val_accuracy: 0.6000 - val_loss: 0.8701
Epoch 7/20
1/1 - 0s - 197ms/step - accuracy: 0.9667 - loss: 0.3254 - val_accuracy: 0.6000 - val_loss: 0.8728
Epoch 8/20
1/1 - 0s - 197ms/step - accuracy: 0.9667 - loss: 0.2957 - val_accuracy: 0.5000 - val_loss: 0.8808
Epoch 9/20
1/1 - 0s - 198ms/step - accuracy: 0.9667 - loss: 0.2693 - val_accuracy: 0.5000 - val_loss: 0.8929
Epoch 10/20
1/1 - 0s -

### 🔚 Conclusion
We have successfully implemented transfer learning with MobileNetV2. We have used the pre-trained MobileNetV2 model and extended it with our own data to classify dogs as female or male.