In [95]:
# Function List
# -------------
# np.arange()
# np.shape
# np.ndim
# np.size
# np.linspace()
# np.sort()
# np.concatenate()
# np.reshape()
# np.vstack()
# np.hstack()
# np.sum()
# np.min()
# np.max()
# np.unique()
# np.transpose() # abbreviation is T
# np.flatten()
# np.ravel()

In [2]:
import numpy as np

In [10]:
a = np.arange(10) # upper bound is exclusive
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a.shape # (row, column) -> (10,)

(10,)

In [12]:
# creating row vector
rowvec = a[np.newaxis, :] # add new axis to x, and fill with all items of the array
rowvec # rowvec is now a mathematical vector

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
# creating column vector
colvec = a[:, np.newaxis]
colvec

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
b = np.array([4, 6, 8])
rowb = b[np.newaxis, :]
colb = b[:, np.newaxis]
rowb

array([[4, 6, 8]])

In [15]:
colb

array([[4],
       [6],
       [8]])

In [16]:
rowb.shape

(1, 3)

In [17]:
colb.shape

(3, 1)

In [18]:
b.shape

(3,)

In [19]:
rowb.ndim

2

In [20]:
b.ndim

1

In [21]:
b.size

3

In [22]:
rowb.size

3

In [23]:
c = np.linspace(0, 9, num = 10) # boundaries are inclusive, num specifies the desired number of instances
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
d = [4, 6, 8]
d

[4, 6, 8]

In [25]:
# d[3] = 2 --> error will occur
d.append(2)
d

[4, 6, 8, 2]

In [26]:
e = np.array([4, 1, 8, 3, 5, 9, 2])
e

array([4, 1, 8, 3, 5, 9, 2])

In [27]:
f = np.sort(e)
f

array([1, 2, 3, 4, 5, 8, 9])

In [28]:
rowb

array([[4, 6, 8]])

In [29]:
g = np.array([2, 8, 1])
rowg = g[np.newaxis, :]

In [30]:
h = np.concatenate((rowb, rowg))
h

array([[4, 6, 8],
       [2, 8, 1]])

In [33]:
h.shape

(2, 3)

In [35]:
h.size

6

In [36]:
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
j = i.reshape(5, 2)
j

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
j.shape

(5, 2)

In [39]:
# Working with indexes of array

In [40]:
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
i[0:5]

array([0, 1, 2, 3, 4])

In [42]:
i[3:7]

array([3, 4, 5, 6])

In [43]:
i[4:]

array([4, 5, 6, 7, 8, 9])

In [44]:
i[:4]

array([0, 1, 2, 3])

In [45]:
i[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
i[-1]

9

In [47]:
# i[-1:-4] --> wrong index order
i[-4:-1]

array([6, 7, 8])

In [48]:
i[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [49]:
i[i>3]

array([4, 5, 6, 7, 8, 9])

In [50]:
i[(i>3) & (i<7)]

array([4, 5, 6])

In [51]:
i[i%2==0]

array([0, 2, 4, 6, 8])

In [61]:
# 2D Arrays

In [62]:
A = np.array([[2, 3,], [5, 7]])
A

array([[2, 3],
       [5, 7]])

In [63]:
A.shape

(2, 2)

In [64]:
B = np.array([[1, 8,], [3, 6]])
B

array([[1, 8],
       [3, 6]])

In [65]:
verstack = np.vstack((A, B))
verstack

array([[2, 3],
       [5, 7],
       [1, 8],
       [3, 6]])

In [66]:
horstack = np.hstack((A, B))
horstack

array([[2, 3, 1, 8],
       [5, 7, 3, 6]])

In [67]:
A+B

array([[ 3, 11],
       [ 8, 13]])

In [68]:
A*B #  this multiplication isn't the multiplication of two matrices!

array([[ 2, 24],
       [15, 42]])

In [69]:
A/B

array([[2.        , 0.375     ],
       [1.66666667, 1.16666667]])

In [70]:
A-B

array([[ 1, -5],
       [ 2,  1]])

In [71]:
# Broadcasting

In [72]:
k = np.array([20, 23, 25, 28])
k

array([20, 23, 25, 28])

In [73]:
k*2

array([40, 46, 50, 56])

In [74]:
k+1

array([21, 24, 26, 29])

In [75]:
(k-2023) * -1

array([2003, 2000, 1998, 1995])

In [76]:
# Significant Operations

In [78]:
k.max()

28

In [79]:
k.min()

20

In [80]:
k.sum()

96

In [81]:
verstack.min()

1

In [82]:
verstack.max()

8

In [83]:
verstack[1, 1]

7

In [84]:
l = np.array([3, 1, 7, 8, 2, 9, 3, 0, 4, 1, 3, 4, 7])
m = np.unique(l)
m

array([0, 1, 2, 3, 4, 7, 8, 9])

In [85]:
# Transpose

In [86]:
verstack.transpose()

array([[2, 5, 1, 3],
       [3, 7, 8, 6]])

In [87]:
verstack.T # shortcut of previous

array([[2, 5, 1, 3],
       [3, 7, 8, 6]])

In [88]:
n = verstack.flatten()
n

array([2, 3, 5, 7, 1, 8, 3, 6])

In [89]:
n[0] = 200
n

array([200,   3,   5,   7,   1,   8,   3,   6])

In [90]:
verstack # the change in n didn't effect verstack

array([[2, 3],
       [5, 7],
       [1, 8],
       [3, 6]])

In [91]:
o = verstack.ravel()
o

array([2, 3, 5, 7, 1, 8, 3, 6])

In [92]:
o[0] = 100
o

array([100,   3,   5,   7,   1,   8,   3,   6])

In [93]:
verstack # the change in n effected verstack

array([[100,   3],
       [  5,   7],
       [  1,   8],
       [  3,   6]])